### ISSUE TITLE
Embed pre-trained model into ROS code.

### ISSUE THREAD

**Issue by bessszilard** [safdark/Automata-Capstone#12]
Pre-trained model can be found here: https://github.com/marcomarasca/CarND-Traffic-Light-Detection/tree/master/saved_models
[On the website](https://github.com/tensorflow/models/tree/master/research/object_detection), they suggest _ssd_inception_v2_coco_ and _faster_rcnn_resnet101_coco_ .
The tensorflow library version can be a problem.

**Comment by naveedhd** [comment]
should we consider this done with #14 ?

**Comment by alikureishy** [comment]
Yes, I think Eugene has completed that already. But maybe you can check with to be 100% sure that there's nothing else remaining?
