### ISSUE TITLE
Create model architecture in model.py file

### ISSUE THREAD

**Issue by alikureishy** [safdark/Automata-Capstone#5]
This file will expose a method:

def create_model_for_training(.....):
      # ... and return the model architecture as below:

      return input, output, loss_function, optimizer ...

This will be used by the tl_trainer.py node. Having this as a separate file allows the architecture to be implemented independently from the trainer.

**Comment by bessszilard** [comment]
I suggest pretrained SSD_GRAPH or FASTER_RCNN. In this case, we have only to fine-tune the existing model.

**Comment by bessszilard** [comment]
Without any fine-tuning I was able to detect traffic light contours on the image in most cases.
![index](https://user-images.githubusercontent.com/48211034/60907958-10eaa100-a27b-11e9-8b3a-480f4a6ec461.png)

**Comment by bessszilard** [comment]
The most elegant method is to fine-tune the model, and the CNN will classifier the traffic lights's color too.
